<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.27">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adriano Porto">
<meta name="author" content="Kauan Brito">

<title>Análise da Taxa de Mortalidade Infantil e Indicadores Socioeconômicos</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="report_files/libs/clipboard/clipboard.min.js"></script>
<script src="report_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="report_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="report_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="report_files/libs/quarto-html/popper.min.js"></script>
<script src="report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="report_files/libs/quarto-html/anchor.min.js"></script>
<link href="report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="report_files/libs/quarto-html/quarto-syntax-highlighting-ed96de9b727972fe78a7b5d16c58bf87.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="report_files/libs/bootstrap/bootstrap-ba858d548ad92676443b74b489ccbdac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> Introdução</a></li>
  <li><a href="#descrição-da-base-de-dados" id="toc-descrição-da-base-de-dados" class="nav-link" data-scroll-target="#descrição-da-base-de-dados"><span class="header-section-number">2</span> Descrição da Base de Dados</a>
  <ul class="collapse">
  <li><a href="#leitura-da-base-de-dados" id="toc-leitura-da-base-de-dados" class="nav-link" data-scroll-target="#leitura-da-base-de-dados"><span class="header-section-number">2.1</span> Leitura da base de dados</a></li>
  <li><a href="#número-de-observações" id="toc-número-de-observações" class="nav-link" data-scroll-target="#número-de-observações"><span class="header-section-number">2.2</span> Número de observações</a></li>
  <li><a href="#estrutura-da-base-de-dados" id="toc-estrutura-da-base-de-dados" class="nav-link" data-scroll-target="#estrutura-da-base-de-dados"><span class="header-section-number">2.3</span> Estrutura da base de dados</a></li>
  <li><a href="#estatísticas-descritivas-detalhadas" id="toc-estatísticas-descritivas-detalhadas" class="nav-link" data-scroll-target="#estatísticas-descritivas-detalhadas"><span class="header-section-number">2.4</span> Estatísticas descritivas detalhadas</a></li>
  <li><a href="#variáveis-da-base-de-dados" id="toc-variáveis-da-base-de-dados" class="nav-link" data-scroll-target="#variáveis-da-base-de-dados"><span class="header-section-number">2.5</span> Variáveis da base de dados</a></li>
  </ul></li>
  <li><a href="#análise-exploratória-de-dados" id="toc-análise-exploratória-de-dados" class="nav-link" data-scroll-target="#análise-exploratória-de-dados"><span class="header-section-number">3</span> Análise Exploratória de Dados</a>
  <ul class="collapse">
  <li><a href="#verificação-de-valores-ausentes" id="toc-verificação-de-valores-ausentes" class="nav-link" data-scroll-target="#verificação-de-valores-ausentes"><span class="header-section-number">3.1</span> Verificação de valores ausentes</a></li>
  <li><a href="#distribuição-da-taxa-de-mortalidade-infantil" id="toc-distribuição-da-taxa-de-mortalidade-infantil" class="nav-link" data-scroll-target="#distribuição-da-taxa-de-mortalidade-infantil"><span class="header-section-number">3.2</span> Distribuição da Taxa de Mortalidade Infantil</a></li>
  <li><a href="#identificação-de-possíveis-outliers" id="toc-identificação-de-possíveis-outliers" class="nav-link" data-scroll-target="#identificação-de-possíveis-outliers"><span class="header-section-number">3.3</span> Identificação de possíveis outliers</a></li>
  </ul></li>
  <li><a href="#análises-bivariadas" id="toc-análises-bivariadas" class="nav-link" data-scroll-target="#análises-bivariadas"><span class="header-section-number">4</span> Análises Bivariadas</a>
  <ul class="collapse">
  <li><a href="#somente-entre-variáveis-numéricas" id="toc-somente-entre-variáveis-numéricas" class="nav-link" data-scroll-target="#somente-entre-variáveis-numéricas"><span class="header-section-number">4.1</span> Somente entre variáveis numéricas</a></li>
  <li><a href="#variável-numérica-em-função-de-categórica" id="toc-variável-numérica-em-função-de-categórica" class="nav-link" data-scroll-target="#variável-numérica-em-função-de-categórica"><span class="header-section-number">4.2</span> Variável numérica em função de categórica</a></li>
  <li><a href="#relação-entre-renda-e-mortalidade-infantil" id="toc-relação-entre-renda-e-mortalidade-infantil" class="nav-link" data-scroll-target="#relação-entre-renda-e-mortalidade-infantil"><span class="header-section-number">4.3</span> Relação entre renda e mortalidade infantil</a></li>
  <li><a href="#relação-entre-saneamento-e-mortalidade-infantil" id="toc-relação-entre-saneamento-e-mortalidade-infantil" class="nav-link" data-scroll-target="#relação-entre-saneamento-e-mortalidade-infantil"><span class="header-section-number">4.4</span> Relação entre saneamento e mortalidade infantil</a></li>
  </ul></li>
  <li><a href="#ajuste-do-modelo-inicial-de-regressão" id="toc-ajuste-do-modelo-inicial-de-regressão" class="nav-link" data-scroll-target="#ajuste-do-modelo-inicial-de-regressão"><span class="header-section-number">5</span> Ajuste do Modelo Inicial de Regressão</a>
  <ul class="collapse">
  <li><a href="#diagnóstico-de-multicolinearidade" id="toc-diagnóstico-de-multicolinearidade" class="nav-link" data-scroll-target="#diagnóstico-de-multicolinearidade"><span class="header-section-number">5.1</span> Diagnóstico de Multicolinearidade</a></li>
  </ul></li>
  <li><a href="#seleção-de-modelo" id="toc-seleção-de-modelo" class="nav-link" data-scroll-target="#seleção-de-modelo"><span class="header-section-number">6</span> Seleção de Modelo</a>
  <ul class="collapse">
  <li><a href="#com-ou-sem-leitos-por-mil-habitantes" id="toc-com-ou-sem-leitos-por-mil-habitantes" class="nav-link" data-scroll-target="#com-ou-sem-leitos-por-mil-habitantes"><span class="header-section-number">6.1</span> Com ou Sem Leitos por Mil Habitantes</a></li>
  <li><a href="#pib-per-capita-ou-renda-per-capita" id="toc-pib-per-capita-ou-renda-per-capita" class="nav-link" data-scroll-target="#pib-per-capita-ou-renda-per-capita"><span class="header-section-number">6.2</span> PIB per capita ou Renda per capita</a>
  <ul class="collapse">
  <li><a href="#apenas-pib-per-capita" id="toc-apenas-pib-per-capita" class="nav-link" data-scroll-target="#apenas-pib-per-capita"><span class="header-section-number">6.2.1</span> Apenas PIB per capita</a></li>
  <li><a href="#apenas-renda-per-capita" id="toc-apenas-renda-per-capita" class="nav-link" data-scroll-target="#apenas-renda-per-capita"><span class="header-section-number">6.2.2</span> Apenas Renda per capita</a></li>
  <li><a href="#comparação-de-valores-aic" id="toc-comparação-de-valores-aic" class="nav-link" data-scroll-target="#comparação-de-valores-aic"><span class="header-section-number">6.2.3</span> Comparação de valores AIC</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#checando-pressupostos-do-mrlm" id="toc-checando-pressupostos-do-mrlm" class="nav-link" data-scroll-target="#checando-pressupostos-do-mrlm"><span class="header-section-number">7</span> Checando pressupostos do MRLM</a>
  <ul class="collapse">
  <li><a href="#plot-do-r-base" id="toc-plot-do-r-base" class="nav-link" data-scroll-target="#plot-do-r-base"><span class="header-section-number">7.1</span> Plot do R base</a></li>
  <li><a href="#checagem-manual-do-easystats" id="toc-checagem-manual-do-easystats" class="nav-link" data-scroll-target="#checagem-manual-do-easystats"><span class="header-section-number">7.2</span> Checagem manual do Easystats</a></li>
  <li><a href="#análise-gráfica-de-todos-os-pressupostos" id="toc-análise-gráfica-de-todos-os-pressupostos" class="nav-link" data-scroll-target="#análise-gráfica-de-todos-os-pressupostos"><span class="header-section-number">7.3</span> Análise gráfica de todos os pressupostos</a></li>
  </ul></li>
  <li><a href="#previsões" id="toc-previsões" class="nav-link" data-scroll-target="#previsões"><span class="header-section-number">8</span> Previsões</a>
  <ul class="collapse">
  <li><a href="#novas-preditoras" id="toc-novas-preditoras" class="nav-link" data-scroll-target="#novas-preditoras"><span class="header-section-number">8.1</span> Novas preditoras</a></li>
  <li><a href="#intervalo-de-confiança" id="toc-intervalo-de-confiança" class="nav-link" data-scroll-target="#intervalo-de-confiança"><span class="header-section-number">8.2</span> Intervalo de Confiança</a></li>
  <li><a href="#intervalo-de-predição" id="toc-intervalo-de-predição" class="nav-link" data-scroll-target="#intervalo-de-predição"><span class="header-section-number">8.3</span> Intervalo de Predição</a></li>
  <li><a href="#comparação-entre-intervalos" id="toc-comparação-entre-intervalos" class="nav-link" data-scroll-target="#comparação-entre-intervalos"><span class="header-section-number">8.4</span> Comparação entre Intervalos</a></li>
  <li><a href="#conclusão" id="toc-conclusão" class="nav-link" data-scroll-target="#conclusão"><span class="header-section-number">8.5</span> Conclusão</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise da Taxa de Mortalidade Infantil e Indicadores Socioeconômicos</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autores</div>
    <div class="quarto-title-meta-contents">
             <p>Adriano Porto </p>
             <p>Kauan Brito </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Data de Publicação</div>
    <div class="quarto-title-meta-contents">
      <p class="date">15 de março de 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introdução" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introdução</h1>
<p>A taxa de mortalidade infantil (TMI) é um dos principais indicadores utilizados para avaliar as condições de saúde e desenvolvimento socioeconômico de uma população. Esse indicador reflete não apenas a qualidade da assistência médica disponível, mas também aspectos estruturais da sociedade, como condições de saneamento, renda, educação e desigualdade social.</p>
<p>Diversos fatores socioeconômicos podem influenciar diretamente os níveis de mortalidade infantil. Entre esses fatores destacam-se o acesso ao saneamento básico, o nível de renda da população, a cobertura de serviços de atenção primária à saúde, o nível educacional da população e indicadores de desigualdade econômica.</p>
<p>Neste estudo busca-se analisar a relação entre a taxa de mortalidade infantil e diferentes indicadores socioeconômicos e de infraestrutura de saúde. Para isso, será utilizada uma base de dados contendo variáveis relacionadas a condições econômicas, sociais e de acesso à saúde.</p>
<p>O objetivo principal desta análise é investigar possíveis associações entre a taxa de mortalidade infantil e variáveis socioeconômicas, além de realizar uma análise exploratória inicial da base de dados.</p>
</section>
<section id="descrição-da-base-de-dados" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Descrição da Base de Dados</h1>
<p>A base de dados utilizada neste estudo contém informações relacionadas a indicadores socioeconômicos e de saúde pública. Cada observação corresponde a uma unidade geográfica, podendo representar estados ou municípios, contendo variáveis explicativas que podem influenciar a taxa de mortalidade infantil.</p>
<section id="leitura-da-base-de-dados" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="leitura-da-base-de-dados"><span class="header-section-number">2.1</span> Leitura da base de dados</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">"dados.xlsx"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>regiao <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>  dados<span class="sc">$</span>regiao,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">"Norte"</span>, <span class="st">"Nordeste"</span>, <span class="st">"Centro-Oeste"</span>, <span class="st">"Sudeste"</span>, <span class="st">"Sul"</span>)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 11
     id   tmi saneamento pib_percapita cobertura_psf analfabetismo  gini   idh
  &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt;         &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1     1  9.99       74.4          25.1          73.4           7.8 0.569 0.95 
2     2 23.7        62.4          19.4          73.3          19.4 0.588 0.938
3     3  1.5        82.4          36.2          72.8           2.7 0.521 0.95 
4     4  2.47       75.4          28.6          68.8           8.9 0.492 0.95 
5     5 16.1        68.3          21.2          78.1          13.5 0.45  0.95 
6     6  1.5        87.2          30.4          94.7           5   0.506 0.95 
# ℹ 3 more variables: renda_percapita &lt;dbl&gt;, leitos_mil &lt;dbl&gt;, regiao &lt;fct&gt;</code></pre>
</div>
</div>
</section>
<section id="número-de-observações" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="número-de-observações"><span class="header-section-number">2.2</span> Número de observações</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 300</code></pre>
</div>
</div>
</section>
<section id="estrutura-da-base-de-dados" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="estrutura-da-base-de-dados"><span class="header-section-number">2.3</span> Estrutura da base de dados</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 300
Columns: 11
$ id              &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…
$ tmi             &lt;dbl&gt; 9.99, 23.74, 1.50, 2.47, 16.11, 1.50, 35.44, 30.30, 10…
$ saneamento      &lt;dbl&gt; 74.4, 62.4, 82.4, 75.4, 68.3, 87.2, 48.0, 52.3, 72.7, …
$ pib_percapita   &lt;dbl&gt; 25.09, 19.41, 36.21, 28.64, 21.22, 30.43, 11.36, 13.41…
$ cobertura_psf   &lt;dbl&gt; 73.4, 73.3, 72.8, 68.8, 78.1, 94.7, 58.8, 59.0, 66.3, …
$ analfabetismo   &lt;dbl&gt; 7.8, 19.4, 2.7, 8.9, 13.5, 5.0, 22.2, 24.1, 7.7, 8.8, …
$ gini            &lt;dbl&gt; 0.569, 0.588, 0.521, 0.492, 0.450, 0.506, 0.552, 0.596…
$ idh             &lt;dbl&gt; 0.950, 0.938, 0.950, 0.950, 0.950, 0.950, 0.802, 0.842…
$ renda_percapita &lt;dbl&gt; 1693, 1445, 2443, 2094, 1451, 2084, 753, 927, 1657, 20…
$ leitos_mil      &lt;dbl&gt; 0.84, 2.21, 2.76, 2.02, 1.60, 2.72, 0.89, 0.20, 0.20, …
$ regiao          &lt;fct&gt; Sul, Nordeste, Sudeste, Sudeste, Nordeste, Sudeste, No…</code></pre>
</div>
</div>
</section>
<section id="estatísticas-descritivas-detalhadas" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="estatísticas-descritivas-detalhadas"><span class="header-section-number">2.4</span> Estatísticas descritivas detalhadas</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">skim</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">dados</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">300</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">11</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">factor</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">10</td>
</tr>
<tr class="even">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: factor</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 38%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: left;">ordered</th>
<th style="text-align: right;">n_unique</th>
<th style="text-align: left;">top_counts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">regiao</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">FALSE</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">Sud: 99, Nor: 81, Sul: 50, Nor: 38</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">id</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">150.50</td>
<td style="text-align: right;">86.75</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">75.75</td>
<td style="text-align: right;">150.50</td>
<td style="text-align: right;">225.25</td>
<td style="text-align: right;">300.00</td>
<td style="text-align: left;">▇▇▇▇▇</td>
</tr>
<tr class="even">
<td style="text-align: left;">tmi</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">19.89</td>
<td style="text-align: right;">12.32</td>
<td style="text-align: right;">1.50</td>
<td style="text-align: right;">9.86</td>
<td style="text-align: right;">18.57</td>
<td style="text-align: right;">28.89</td>
<td style="text-align: right;">48.82</td>
<td style="text-align: left;">▇▇▆▅▂</td>
</tr>
<tr class="odd">
<td style="text-align: left;">saneamento</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.98</td>
<td style="text-align: right;">63.26</td>
<td style="text-align: right;">16.22</td>
<td style="text-align: right;">14.60</td>
<td style="text-align: right;">52.15</td>
<td style="text-align: right;">63.80</td>
<td style="text-align: right;">74.40</td>
<td style="text-align: right;">99.50</td>
<td style="text-align: left;">▁▃▇▇▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">pib_percapita</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">20.11</td>
<td style="text-align: right;">11.59</td>
<td style="text-align: right;">3.00</td>
<td style="text-align: right;">11.67</td>
<td style="text-align: right;">19.64</td>
<td style="text-align: right;">27.22</td>
<td style="text-align: right;">53.87</td>
<td style="text-align: left;">▇▇▆▂▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">cobertura_psf</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">64.44</td>
<td style="text-align: right;">12.72</td>
<td style="text-align: right;">32.70</td>
<td style="text-align: right;">56.08</td>
<td style="text-align: right;">64.95</td>
<td style="text-align: right;">73.40</td>
<td style="text-align: right;">98.80</td>
<td style="text-align: left;">▂▅▇▅▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">analfabetismo</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">11.95</td>
<td style="text-align: right;">6.23</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">6.80</td>
<td style="text-align: right;">11.40</td>
<td style="text-align: right;">16.10</td>
<td style="text-align: right;">30.40</td>
<td style="text-align: left;">▅▇▇▃▁</td>
</tr>
<tr class="odd">
<td style="text-align: left;">gini</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.07</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.56</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.73</td>
<td style="text-align: left;">▁▆▇▅▂</td>
</tr>
<tr class="even">
<td style="text-align: left;">idh</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">0.87</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">0.60</td>
<td style="text-align: right;">0.79</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: right;">0.95</td>
<td style="text-align: left;">▁▂▁▂▇</td>
</tr>
<tr class="odd">
<td style="text-align: left;">renda_percapita</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: right;">1419.57</td>
<td style="text-align: right;">808.69</td>
<td style="text-align: right;">150.00</td>
<td style="text-align: right;">797.25</td>
<td style="text-align: right;">1411.00</td>
<td style="text-align: right;">1947.25</td>
<td style="text-align: right;">3710.00</td>
<td style="text-align: left;">▇▇▇▃▁</td>
</tr>
<tr class="even">
<td style="text-align: left;">leitos_mil</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.99</td>
<td style="text-align: right;">1.03</td>
<td style="text-align: right;">0.70</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.94</td>
<td style="text-align: right;">1.46</td>
<td style="text-align: right;">3.30</td>
<td style="text-align: left;">▇▆▃▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="variáveis-da-base-de-dados" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="variáveis-da-base-de-dados"><span class="header-section-number">2.5</span> Variáveis da base de dados</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 41%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Variável</th>
<th>Significado</th>
<th>Unidade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>tmi</td>
<td>Taxa de mortalidade infantil</td>
<td>óbitos por 1000 nascidos vivos</td>
</tr>
<tr class="even">
<td>saneamento</td>
<td>Percentual da população com acesso a saneamento básico</td>
<td>%</td>
</tr>
<tr class="odd">
<td>pib_percapita</td>
<td>Produto Interno Bruto per capita</td>
<td>R$</td>
</tr>
<tr class="even">
<td>psf</td>
<td>Cobertura da Estratégia Saúde da Família</td>
<td>%</td>
</tr>
<tr class="odd">
<td>analfabetismo</td>
<td>Taxa de analfabetismo</td>
<td>%</td>
</tr>
<tr class="even">
<td>gini</td>
<td>Índice de desigualdade de renda</td>
<td>0 a 1</td>
</tr>
<tr class="odd">
<td>idh</td>
<td>Índice de Desenvolvimento Humano</td>
<td>0 a 1</td>
</tr>
<tr class="even">
<td>renda_percapita</td>
<td>Renda média per capita</td>
<td>R$</td>
</tr>
<tr class="odd">
<td>leitos</td>
<td>Número de leitos hospitalares</td>
<td>leitos por 1000 habitantes</td>
</tr>
<tr class="even">
<td>regiao</td>
<td>Região geográfica do Brasil (Norte, Nordeste, Centro-Oeste, Sudeste, Sul)</td>
<td>categórica</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="análise-exploratória-de-dados" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Análise Exploratória de Dados</h1>
<p>Antes da construção de modelos estatísticos, é importante realizar uma análise exploratória da base de dados. Essa etapa permite compreender melhor as características das variáveis, identificar possíveis valores ausentes e detectar a presença de valores extremos (outliers).</p>
<section id="verificação-de-valores-ausentes" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="verificação-de-valores-ausentes"><span class="header-section-number">3.1</span> Verificação de valores ausentes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colSums</span>(<span class="fu">is.na</span>(dados))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>             id             tmi      saneamento   pib_percapita   cobertura_psf 
              0               0               5               0               4 
  analfabetismo            gini             idh renda_percapita      leitos_mil 
              3               0               0               0               3 
         regiao 
              0 </code></pre>
</div>
</div>
</section>
<section id="distribuição-da-taxa-de-mortalidade-infantil" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="distribuição-da-taxa-de-mortalidade-infantil"><span class="header-section-number">3.2</span> Distribuição da Taxa de Mortalidade Infantil</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x =</span> tmi)) <span class="sc">+</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">fill =</span> <span class="st">"lightblue"</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Distribuição da Taxa de Mortalidade Infantil"</span>,</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"TMI"</span>,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequência"</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="identificação-de-possíveis-outliers" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="identificação-de-possíveis-outliers"><span class="header-section-number">3.3</span> Identificação de possíveis outliers</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  dados<span class="sc">$</span>tmi,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Boxplot da Taxa de Mortalidade Infantil"</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"TMI"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise exploratória permite identificar padrões iniciais nos dados e possíveis inconsistências na base de dados, como valores ausentes ou observações extremas.</p>
</section>
</section>
<section id="análises-bivariadas" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Análises Bivariadas</h1>
<section id="somente-entre-variáveis-numéricas" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="somente-entre-variáveis-numéricas"><span class="header-section-number">4.1</span> Somente entre variáveis numéricas</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>dados_num <span class="ot">&lt;-</span> dados <span class="sc">%&gt;%</span> <span class="fu">select_if</span>(is.numeric)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>corr_matrix <span class="ot">&lt;-</span> <span class="fu">cor</span>(dados_num, <span class="at">use =</span> <span class="st">"complete.obs"</span>)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>corr_matrix</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                         id         tmi  saneamento pib_percapita cobertura_psf
id               1.00000000  0.05572141 -0.06349452   -0.04288378   -0.07267058
tmi              0.05572141  1.00000000 -0.85115146   -0.89982770   -0.55900389
saneamento      -0.06349452 -0.85115146  1.00000000    0.71049678    0.39192419
pib_percapita   -0.04288378 -0.89982770  0.71049678    1.00000000    0.57965857
cobertura_psf   -0.07267058 -0.55900389  0.39192419    0.57965857    1.00000000
analfabetismo   -0.03356514  0.76416643 -0.69466637   -0.56610033   -0.19850305
gini             0.07057474  0.62638193 -0.49069753   -0.64278201   -0.44274169
idh             -0.07200699 -0.83249153  0.61109906    0.82482297    0.51343627
renda_percapita -0.03850265 -0.88859628  0.69886259    0.98962862    0.60476741
leitos_mil      -0.09451450 -0.07013885  0.04628789    0.10633944    0.09951698
                analfabetismo         gini         idh renda_percapita
id                -0.03356514  0.070574744 -0.07200699     -0.03850265
tmi                0.76416643  0.626381929 -0.83249153     -0.88859628
saneamento        -0.69466637 -0.490697527  0.61109906      0.69886259
pib_percapita     -0.56610033 -0.642782006  0.82482297      0.98962862
cobertura_psf     -0.19850305 -0.442741695  0.51343627      0.60476741
analfabetismo      1.00000000  0.316760029 -0.63223917     -0.52344981
gini               0.31676003  1.000000000 -0.55575414     -0.67599082
idh               -0.63223917 -0.555754135  1.00000000      0.82560233
renda_percapita   -0.52344981 -0.675990819  0.82560233      1.00000000
leitos_mil        -0.02574811  0.003553445  0.03713843      0.08589125
                  leitos_mil
id              -0.094514505
tmi             -0.070138851
saneamento       0.046287886
pib_percapita    0.106339436
cobertura_psf    0.099516978
analfabetismo   -0.025748107
gini             0.003553445
idh              0.037138427
renda_percapita  0.085891254
leitos_mil       1.000000000</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">corrplot</span>(</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>  corr_matrix,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"color"</span>,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"upper"</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">addCoef.col =</span> <span class="st">"black"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">number.cex =</span> <span class="fl">0.65</span>,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.cex =</span> <span class="fl">0.75</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">tl.srt =</span> <span class="dv">45</span></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise da matriz de correlação indica relações importantes entre as variáveis socioeconômicas e a taxa de mortalidade infantil (TMI).</p>
<p>Observa-se uma forte correlação negativa entre TMI e renda per capita (-0.89), indicando que regiões ou municípios com maior renda tendem a apresentar menores níveis de mortalidade infantil. De forma semelhante, o Índice de Desenvolvimento Humano (IDH) também apresenta correlação negativa elevada com a TMI (-0.83), sugerindo que melhores condições de desenvolvimento humano estão associadas a menores taxas de mortalidade infantil.</p>
<p>O acesso ao saneamento também apresenta correlação negativa significativa com a mortalidade infantil (-0.85), reforçando a importância da infraestrutura sanitária para a saúde pública.</p>
<p>Por outro lado, o analfabetismo apresenta correlação positiva com a TMI (0.76), indicando que locais com maiores níveis de analfabetismo tendem a registrar maiores taxas de mortalidade infantil.</p>
<p>Esses resultados sugerem que fatores socioeconômicos, educacionais e de infraestrutura estão fortemente associados às condições de saúde infantil.</p>
</section>
<section id="variável-numérica-em-função-de-categórica" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="variável-numérica-em-função-de-categórica"><span class="header-section-number">4.2</span> Variável numérica em função de categórica</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x =</span> regiao, <span class="at">y =</span> tmi)) <span class="sc">+</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">"lightblue"</span>) <span class="sc">+</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Taxa de Mortalidade Infantil por Região do Brasil"</span>,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Região"</span>,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"TMI"</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Observa-se que a taxa de mortalidade infantil apresenta diferenças importantes entre as cinco regiões do Brasil (Norte, Nordeste, Centro-Oeste, Sudeste e Sul).</p>
<p>As regiões Norte e Nordeste apresentam medianas mais elevadas de TMI, além de maior dispersão dos valores, indicando maior variabilidade entre os municípios dessas regiões.</p>
<p>Em contraste, as regiões Sul e Sudeste apresentam medianas significativamente menores, sugerindo melhores condições socioeconômicas e de acesso a serviços de saúde.</p>
<p>A região Centro-Oeste apresenta valores intermediários, situando-se entre os grupos de maior e menor mortalidade infantil.</p>
<p>Esses resultados indicam desigualdades regionais importantes nas condições de saúde e desenvolvimento.</p>
</section>
<section id="relação-entre-renda-e-mortalidade-infantil" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="relação-entre-renda-e-mortalidade-infantil"><span class="header-section-number">4.3</span> Relação entre renda e mortalidade infantil</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x =</span> renda_percapita, <span class="at">y =</span> tmi)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Renda per capita vs Mortalidade Infantil"</span>,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Renda per capita"</span>,</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"TMI"</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A relação entre renda per capita e mortalidade infantil apresenta um padrão claramente negativo.</p>
<p>Observa-se que à medida que a renda per capita aumenta, a taxa de mortalidade infantil tende a diminuir. A linha de regressão ajustada confirma essa tendência, indicando uma associação linear negativa entre as variáveis.</p>
<p>Esse resultado sugere que municípios com maior renda possuem melhores condições de vida, maior acesso a serviços de saúde, nutrição adequada e infraestrutura básica, fatores que contribuem para a redução da mortalidade infantil.</p>
</section>
<section id="relação-entre-saneamento-e-mortalidade-infantil" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="relação-entre-saneamento-e-mortalidade-infantil"><span class="header-section-number">4.4</span> Relação entre saneamento e mortalidade infantil</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(dados, <span class="fu">aes</span>(<span class="at">x =</span> saneamento, <span class="at">y =</span> tmi)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Saneamento vs Mortalidade Infantil"</span>,</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Acesso ao saneamento (%)"</span>,</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"TMI"</span></span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A análise do gráfico indica uma relação negativa entre acesso ao saneamento e mortalidade infantil.</p>
<p>Observa-se que municípios com maior porcentagem de acesso ao saneamento tendem a apresentar menores taxas de mortalidade infantil. A linha de regressão reforça essa tendência, indicando uma associação inversa entre as variáveis.</p>
<p>Esse resultado evidencia a importância do saneamento básico para a saúde pública, uma vez que melhores condições sanitárias reduzem a exposição a doenças infecciosas e melhoram as condições de vida da população.</p>
</section>
</section>
<section id="ajuste-do-modelo-inicial-de-regressão" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Ajuste do Modelo Inicial de Regressão</h1>
<p>Inicialmente foi ajustado um modelo de regressão linear múltipla considerando todas as variáveis explicativas disponíveis na base de dados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>modelo_inicial <span class="ot">&lt;-</span> <span class="fu">lm</span>(tmi <span class="sc">~</span> saneamento <span class="sc">+</span> pib_percapita <span class="sc">+</span> cobertura_psf <span class="sc">+</span> analfabetismo </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>                     <span class="sc">+</span> gini <span class="sc">+</span> idh <span class="sc">+</span> renda_percapita <span class="sc">+</span> leitos_mil <span class="sc">+</span> regiao, <span class="at">data =</span> dados)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_inicial)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tmi ~ saneamento + pib_percapita + cobertura_psf + 
    analfabetismo + gini + idh + renda_percapita + leitos_mil + 
    regiao, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.9691 -1.9633 -0.1574  1.7480  8.6566 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         48.330419   3.902576  12.384  &lt; 2e-16 ***
saneamento          -0.171109   0.019995  -8.558 8.58e-16 ***
pib_percapita       -0.138327   0.124559  -1.111 0.267753    
cobertura_psf       -0.092532   0.016702  -5.540 7.13e-08 ***
analfabetismo        0.388790   0.061298   6.343 9.38e-10 ***
gini                11.673323   3.294386   3.543 0.000465 ***
idh                -15.201162   3.207358  -4.739 3.46e-06 ***
renda_percapita     -0.003950   0.001859  -2.124 0.034542 *  
leitos_mil           0.030203   0.239846   0.126 0.899883    
regiaoNordeste       0.138602   0.559327   0.248 0.804476    
regiaoCentro-Oeste  -1.871339   0.945829  -1.979 0.048879 *  
regiaoSudeste       -2.214032   0.822309  -2.692 0.007533 ** 
regiaoSul           -2.350338   0.869009  -2.705 0.007270 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.712 on 272 degrees of freedom
  (15 observations deleted due to missingness)
Multiple R-squared:  0.9515,    Adjusted R-squared:  0.9493 
F-statistic: 444.3 on 12 and 272 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Observa-se que o coeficiente de determinação ajustado (R² ajustado) obtido foi de 0.9493, indicando que aproximadamente 94,93% da variabilidade da TMI é explicada pelas variáveis independentes incluídas no modelo, o que sugere um bom nível de ajuste aos dados.</p>
<p>Temos também que a variável leitos_mil, que indica o número de leitos hospitalares por mil habitantes, apresenta valor-p elevado, indicando menor evidência de associação com a variável resposta do modelo.</p>
<section id="diagnóstico-de-multicolinearidade" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="diagnóstico-de-multicolinearidade"><span class="header-section-number">5.1</span> Diagnóstico de Multicolinearidade</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_inicial)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                     GVIF Df GVIF^(1/(2*Df))
saneamento       3.950051  1        1.987474
pib_percapita   78.995250  1        8.887927
cobertura_psf    1.725906  1        1.313737
analfabetismo    5.415994  1        2.327229
gini             2.001197  1        1.414637
idh              4.759025  1        2.181519
renda_percapita 85.884282  1        9.267377
leitos_mil       1.070969  1        1.034876
regiao           6.190327  4        1.255926</code></pre>
</div>
</div>
<p>A análise de multicolinearidade do modelo inicial, através do VIF, indicou uma alta correlação entre pib_percapita e renda_percapita.</p>
<p>Esse resultado é esperado, visto que, além do que foi exposto pela matriz de correlação da análise bivariada dos dados, ambas representam indicadores de nível econômico da população,. Dessa forma, na etapa de seleção do melhor modelo, será considerada a remoção de uma dessas variáveis a fim de reduzir o problema de multicolinearidade.</p>
</section>
</section>
<section id="seleção-de-modelo" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Seleção de Modelo</h1>
<section id="com-ou-sem-leitos-por-mil-habitantes" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="com-ou-sem-leitos-por-mil-habitantes"><span class="header-section-number">6.1</span> Com ou Sem Leitos por Mil Habitantes</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>modelo_sem_leitos <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_inicial, . <span class="sc">~</span> . <span class="sc">-</span> leitos_mil)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_sem_leitos)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tmi ~ saneamento + pib_percapita + cobertura_psf + 
    analfabetismo + gini + idh + renda_percapita + regiao, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.9439 -1.9591 -0.1769  1.7438  8.6669 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         48.546180   3.867076  12.554  &lt; 2e-16 ***
saneamento          -0.168661   0.019699  -8.562 7.90e-16 ***
pib_percapita       -0.137200   0.122287  -1.122 0.262859    
cobertura_psf       -0.091893   0.016483  -5.575 5.89e-08 ***
analfabetismo        0.389987   0.060928   6.401 6.61e-10 ***
gini                11.239609   3.235335   3.474 0.000595 ***
idh                -15.272965   3.179523  -4.804 2.56e-06 ***
renda_percapita     -0.004027   0.001834  -2.196 0.028944 *  
regiaoNordeste       0.164035   0.554554   0.296 0.767608    
regiaoCentro-Oeste  -1.834676   0.939356  -1.953 0.051816 .  
regiaoSudeste       -2.223071   0.817353  -2.720 0.006946 ** 
regiaoSul           -2.359487   0.861637  -2.738 0.006576 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.698 on 276 degrees of freedom
  (12 observations deleted due to missingness)
Multiple R-squared:  0.9522,    Adjusted R-squared:  0.9503 
F-statistic: 499.5 on 11 and 276 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_inicial)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1392.245</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_sem_leitos)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1402.693</code></pre>
</div>
</div>
<p>Foi avaliada a remoção da variável leitos_mil, uma vez que essa variável apresentou p-valor elevado no modelo inicial. Para isso, foi ajustado um modelo alternativo excluindo essa variável.</p>
<p>Observou-se que o R² ajustado apresentou pequeno aumento, passando de aproximadamente 0.9493 para 0.9503, indicando leve melhora na proporção de variabilidade explicada pelo modelo.</p>
<p>Entretanto, ao comparar os modelos utilizando o Critério de Informação de Akaike (AIC), verificou-se que o modelo inicial apresentou AIC = 1392,245, enquanto o modelo sem a variável leitos_mil apresentou AIC = 1402,693.</p>
<p>Como a diferença nos valores de AIC foi maior que 10, conclui-se que a remoção da variável leitos por mil habitantes resultou em pior desempenho do modelo. Dessa forma, optou-se por manter essa variável no modelo.</p>
</section>
<section id="pib-per-capita-ou-renda-per-capita" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="pib-per-capita-ou-renda-per-capita"><span class="header-section-number">6.2</span> PIB per capita ou Renda per capita</h2>
<section id="apenas-pib-per-capita" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="apenas-pib-per-capita"><span class="header-section-number">6.2.1</span> Apenas PIB per capita</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>modelo_apenas_pib <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_inicial, . <span class="sc">~</span> . <span class="sc">-</span> renda_percapita)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_apenas_pib)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tmi ~ saneamento + pib_percapita + cobertura_psf + 
    analfabetismo + gini + idh + leitos_mil + regiao, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-7.4769 -1.8333 -0.1165  1.6979  8.6422 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         48.14659    3.92664  12.262  &lt; 2e-16 ***
saneamento          -0.18006    0.01967  -9.153  &lt; 2e-16 ***
pib_percapita       -0.39409    0.03214 -12.262  &lt; 2e-16 ***
cobertura_psf       -0.09786    0.01662  -5.889 1.14e-08 ***
analfabetismo        0.38379    0.06165   6.226 1.80e-09 ***
gini                13.50565    3.19986   4.221 3.32e-05 ***
idh                -15.94191    3.20880  -4.968 1.19e-06 ***
leitos_mil           0.08416    0.24003   0.351   0.7261    
regiaoNordeste       0.10281    0.56266   0.183   0.8551    
regiaoCentro-Oeste  -1.74789    0.95010  -1.840   0.0669 .  
regiaoSudeste       -1.68911    0.78934  -2.140   0.0332 *  
regiaoSul           -1.86679    0.84405  -2.212   0.0278 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.73 on 273 degrees of freedom
  (15 observations deleted due to missingness)
Multiple R-squared:  0.9507,    Adjusted R-squared:  0.9487 
F-statistic: 478.2 on 11 and 273 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="apenas-renda-per-capita" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="apenas-renda-per-capita"><span class="header-section-number">6.2.2</span> Apenas Renda per capita</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>modelo_apenas_renda <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_inicial, . <span class="sc">~</span> . <span class="sc">-</span> pib_percapita)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_apenas_renda)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = tmi ~ saneamento + cobertura_psf + analfabetismo + 
    gini + idh + renda_percapita + leitos_mil + regiao, data = dados)

Residuals:
    Min      1Q  Median      3Q     Max 
-6.6989 -1.9321 -0.1331  1.7600  8.5183 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         4.865e+01  3.894e+00  12.494  &lt; 2e-16 ***
saneamento         -1.689e-01  1.990e-02  -8.485 1.39e-15 ***
cobertura_psf      -9.087e-02  1.664e-02  -5.460 1.07e-07 ***
analfabetismo       3.921e-01  6.125e-02   6.402 6.67e-10 ***
gini                1.101e+01  3.240e+00   3.396 0.000785 ***
idh                -1.523e+01  3.209e+00  -4.746 3.34e-06 ***
renda_percapita    -5.946e-03  4.769e-04 -12.468  &lt; 2e-16 ***
leitos_mil         -5.685e-03  2.378e-01  -0.024 0.980941    
regiaoNordeste      1.504e-01  5.595e-01   0.269 0.788204    
regiaoCentro-Oeste -1.886e+00  9.461e-01  -1.993 0.047263 *  
regiaoSudeste      -2.469e+00  7.900e-01  -3.125 0.001969 ** 
regiaoSul          -2.581e+00  8.443e-01  -3.057 0.002461 ** 
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.714 on 273 degrees of freedom
  (15 observations deleted due to missingness)
Multiple R-squared:  0.9512,    Adjusted R-squared:  0.9493 
F-statistic: 484.2 on 11 and 273 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="comparação-de-valores-aic" class="level3" data-number="6.2.3">
<h3 data-number="6.2.3" class="anchored" data-anchor-id="comparação-de-valores-aic"><span class="header-section-number">6.2.3</span> Comparação de valores AIC</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_apenas_pib)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1394.935</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">AIC</span>(modelo_apenas_renda)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1391.534</code></pre>
</div>
</div>
<p>Considerando a forte multicolinearidade observada entre as variáveis PIB per capita e Renda per capita, foram ajustados dois modelos alternativos: um mantendo apenas a variável PIB per capita e outro mantendo apenas a variável renda per capita.</p>
<p>Observou-se que o modelo contendo apenas PIB per capita apresentou R² ajustado = 0,9487 e AIC = 1394,935, enquanto o modelo contendo apenas renda per capita apresentou R² ajustado = 0,9493 e AIC = 1391,534.</p>
<p>Como o modelo com renda per capita apresentou maior poder explicativo e menor valor de AIC, conclui-se que ele apresenta melhor desempenho. Dessa forma, optou-se por manter a variável renda per capita e remover a variável PIB per capita, resultando em um modelo mais parcimonioso e estatisticamente adequado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>modelo_final <span class="ot">&lt;-</span> <span class="fu">update</span>(modelo_inicial, . <span class="sc">~</span> . <span class="sc">-</span> pib_percapita)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">vif</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    GVIF Df GVIF^(1/(2*Df))
saneamento      3.909669  1        1.977288
cobertura_psf   1.712071  1        1.308461
analfabetismo   5.403114  1        2.324460
gini            1.934448  1        1.390844
idh             4.758719  1        2.181449
renda_percapita 5.645016  1        2.375924
leitos_mil      1.051526  1        1.025439
regiao          4.973436  4        1.222031</code></pre>
</div>
</div>
<p>Observou-se que as variáveis de renda e analfabetismo apresentaram valores VIF maiores que 5, porém inferiores a 10, indicando multicolinearidade moderada.</p>
<p>Tal resultado é esperado, uma vez que ambas as variáveis representam indicadores socioeconômicos relacionados ao nível de desenvolvimento, sendo plausível a existência de correlação entre elas. Como os valores de VIF permanecem abaixo do limite crítico frequentemente utilizado (VIF &gt; 10), conclui-se que não há evidência de multicolinearidade severa capaz de comprometer a estabilidade das estimativas do modelo.</p>
<p>Dessa forma, optou-se por manter ambas as variáveis no modelo, considerando sua relevância interpretativa para explicar a variabilidade da taxa de mortalidade infantil.</p>
</section>
</section>
</section>
<section id="checando-pressupostos-do-mrlm" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Checando pressupostos do MRLM</h1>
<section id="plot-do-r-base" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="plot-do-r-base"><span class="header-section-number">7.1</span> Plot do R base</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-23-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-23-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-23-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="checagem-manual-do-easystats" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="checagem-manual-do-easystats"><span class="header-section-number">7.2</span> Checagem manual do Easystats</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_normality</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: residuals appear as normally distributed (p = 0.219).</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_heteroscedasticity</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Error variance appears to be homoscedastic (p = 0.609).</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_outliers</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: No outliers detected.
- Based on the following method and threshold: cook (0.92).
- For variable: (Whole model)</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_collinearity</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Check for Multicollinearity

Low Correlation

          Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
    saneamento 3.91 [3.25, 4.77]     1.98      0.26     [0.21, 0.31]
 cobertura_psf 1.71 [1.49, 2.04]     1.31      0.58     [0.49, 0.67]
          gini 1.93 [1.67, 2.31]     1.39      0.52     [0.43, 0.60]
           idh 4.76 [3.93, 5.83]     2.18      0.21     [0.17, 0.25]
    leitos_mil 1.05 [1.00, 1.55]     1.03      0.95     [0.65, 1.00]
        regiao 4.97 [4.10, 6.09]     1.22      0.20     [0.16, 0.24]

Moderate Correlation

            Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI
   analfabetismo 5.40 [4.44, 6.63]     2.32      0.19     [0.15, 0.22]
 renda_percapita 5.65 [4.64, 6.93]     2.38      0.18     [0.14, 0.22]</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_autocorrelation</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OK: Residuals appear to be independent and not autocorrelated (p = 0.824).</code></pre>
</div>
</div>
</section>
<section id="análise-gráfica-de-todos-os-pressupostos" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="análise-gráfica-de-todos-os-pressupostos"><span class="header-section-number">7.3</span> Análise gráfica de todos os pressupostos</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">check_model</span>(modelo_final)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="report_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="480"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="previsões" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Previsões</h1>
<p>Para realizar previsões com o modelo ajustado, é importante considerar valores das variáveis explicativas dentro dos intervalos observados na base de dados. Isso evita extrapolações que podem comprometer a confiabilidade das estimativas produzidas pelo modelo.</p>
<p>Assim, inicialmente apresenta-se um breve resumo das variáveis presentes na base de dados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 300
Columns: 11
$ id              &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,…
$ tmi             &lt;dbl&gt; 9.99, 23.74, 1.50, 2.47, 16.11, 1.50, 35.44, 30.30, 10…
$ saneamento      &lt;dbl&gt; 74.4, 62.4, 82.4, 75.4, 68.3, 87.2, 48.0, 52.3, 72.7, …
$ pib_percapita   &lt;dbl&gt; 25.09, 19.41, 36.21, 28.64, 21.22, 30.43, 11.36, 13.41…
$ cobertura_psf   &lt;dbl&gt; 73.4, 73.3, 72.8, 68.8, 78.1, 94.7, 58.8, 59.0, 66.3, …
$ analfabetismo   &lt;dbl&gt; 7.8, 19.4, 2.7, 8.9, 13.5, 5.0, 22.2, 24.1, 7.7, 8.8, …
$ gini            &lt;dbl&gt; 0.569, 0.588, 0.521, 0.492, 0.450, 0.506, 0.552, 0.596…
$ idh             &lt;dbl&gt; 0.950, 0.938, 0.950, 0.950, 0.950, 0.950, 0.802, 0.842…
$ renda_percapita &lt;dbl&gt; 1693, 1445, 2443, 2094, 1451, 2084, 753, 927, 1657, 20…
$ leitos_mil      &lt;dbl&gt; 0.84, 2.21, 2.76, 2.02, 1.60, 2.72, 0.89, 0.20, 0.20, …
$ regiao          &lt;fct&gt; Sul, Nordeste, Sudeste, Sudeste, Nordeste, Sudeste, No…</code></pre>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id              tmi           saneamento    pib_percapita  
 Min.   :  1.00   Min.   : 1.500   Min.   :14.60   Min.   : 3.00  
 1st Qu.: 75.75   1st Qu.: 9.863   1st Qu.:52.15   1st Qu.:11.68  
 Median :150.50   Median :18.570   Median :63.80   Median :19.64  
 Mean   :150.50   Mean   :19.890   Mean   :63.26   Mean   :20.11  
 3rd Qu.:225.25   3rd Qu.:28.890   3rd Qu.:74.40   3rd Qu.:27.22  
 Max.   :300.00   Max.   :48.820   Max.   :99.50   Max.   :53.87  
                                   NA's   :5                      
 cobertura_psf   analfabetismo        gini             idh        
 Min.   :32.70   Min.   : 0.00   Min.   :0.3630   Min.   :0.5980  
 1st Qu.:56.08   1st Qu.: 6.80   1st Qu.:0.5020   1st Qu.:0.7945  
 Median :64.95   Median :11.40   Median :0.5550   Median :0.9500  
 Mean   :64.44   Mean   :11.95   Mean   :0.5515   Mean   :0.8684  
 3rd Qu.:73.40   3rd Qu.:16.10   3rd Qu.:0.6022   3rd Qu.:0.9500  
 Max.   :98.80   Max.   :30.40   Max.   :0.7340   Max.   :0.9500  
 NA's   :4       NA's   :3                                        
 renda_percapita    leitos_mil             regiao  
 Min.   : 150.0   Min.   :0.200   Norte       :38  
 1st Qu.: 797.2   1st Qu.:0.400   Nordeste    :81  
 Median :1411.0   Median :0.940   Centro-Oeste:32  
 Mean   :1419.6   Mean   :1.029   Sudeste     :99  
 3rd Qu.:1947.2   3rd Qu.:1.460   Sul         :50  
 Max.   :3710.0   Max.   :3.300                    
                  NA's   :3                        </code></pre>
</div>
</div>
<p>A partir do resumo das variáveis observa-se que a taxa de mortalidade infantil (TMI) varia aproximadamente entre 1,5 e 48,8 óbitos por mil nascidos vivos, com média próxima de 19,89.</p>
<p>Entre as variáveis explicativas, o acesso ao saneamento varia aproximadamente entre 14,6% e 99,5%, enquanto a renda per capita apresenta valores entre 150 e 3710 unidades monetárias. Indicadores como analfabetismo, cobertura da atenção básica à saúde e índice de desenvolvimento humano também apresentam variação relevante entre as observações.</p>
<p>Esses intervalos permitem verificar que os valores utilizados nas previsões se encontram dentro de cenários plausíveis observados na base de dados.</p>
<section id="novas-preditoras" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="novas-preditoras"><span class="header-section-number">8.1</span> Novas preditoras</h2>
<p>Para ilustrar o processo de previsão utilizando o modelo ajustado, foram definidos três cenários hipotéticos contendo diferentes combinações de valores para as variáveis explicativas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a>novas.preditoras <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">saneamento =</span> <span class="fu">c</span>(<span class="dv">40</span>, <span class="dv">70</span>, <span class="dv">90</span>),</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">cobertura_psf =</span> <span class="fu">c</span>(<span class="dv">50</span>, <span class="dv">75</span>, <span class="dv">90</span>),</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">analfabetismo =</span> <span class="fu">c</span>(<span class="dv">15</span>, <span class="dv">8</span>, <span class="dv">3</span>),</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">gini =</span> <span class="fu">c</span>(<span class="fl">0.55</span>, <span class="fl">0.50</span>, <span class="fl">0.45</span>),</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">idh =</span> <span class="fu">c</span>(<span class="fl">0.65</span>, <span class="fl">0.75</span>, <span class="fl">0.85</span>),</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">renda_percapita =</span> <span class="fu">c</span>(<span class="dv">600</span>, <span class="dv">1200</span>, <span class="dv">2500</span>),</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">leitos_mil =</span> <span class="fu">c</span>(<span class="fl">1.0</span>, <span class="fl">2.0</span>, <span class="fl">3.0</span>),</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">regiao =</span> <span class="fu">factor</span>(</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">"Nordeste"</span>, <span class="st">"Centro-Oeste"</span>, <span class="st">"Sudeste"</span>),</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">levels =</span> <span class="fu">levels</span>(dados<span class="sc">$</span>regiao)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>novas.preditoras <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 17%">
<col style="width: 12%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">saneamento</th>
<th style="text-align: right;">cobertura_psf</th>
<th style="text-align: right;">analfabetismo</th>
<th style="text-align: right;">gini</th>
<th style="text-align: right;">idh</th>
<th style="text-align: right;">renda_percapita</th>
<th style="text-align: right;">leitos_mil</th>
<th style="text-align: left;">regiao</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">40</td>
<td style="text-align: right;">50</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">600</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Nordeste</td>
</tr>
<tr class="even">
<td style="text-align: right;">70</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.50</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">1200</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Centro-Oeste</td>
</tr>
<tr class="odd">
<td style="text-align: right;">90</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0.45</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">2500</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Sudeste</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Os cenários representam diferentes níveis de desenvolvimento socioeconômico.</p>
<p>O primeiro cenário apresenta menor acesso ao saneamento, maior taxa de analfabetismo e menor renda per capita, características associadas a contextos socioeconômicos menos favorecidos.</p>
<p>O segundo cenário apresenta condições intermediárias em relação aos indicadores analisados.</p>
<p>Já o terceiro cenário representa um contexto mais desenvolvido, com maior acesso ao saneamento, menor taxa de analfabetismo, maior renda per capita e maior disponibilidade de leitos hospitalares.</p>
</section>
<section id="intervalo-de-confiança" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="intervalo-de-confiança"><span class="header-section-number">8.2</span> Intervalo de Confiança</h2>
<p>Um <strong>intervalo de confiança</strong> captura a incerteza associada à estimativa do <strong>valor médio esperado da variável resposta</strong>, dado um conjunto específico de valores para as variáveis explicativas.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>tab_IC <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  modelo_final,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  novas.preditoras,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">"confidence"</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>tab_IC <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tab_IC)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(tab_IC) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Media_Prevista"</span>,</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Limite_Inferior"</span>,</span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Limite_Superior"</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>tab_IC</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Media_Prevista Limite_Inferior Limite_Superior
1      35.962273       34.582894       37.341652
2      18.197336       16.798650       19.596021
3       1.104733       -0.633686        2.843153</code></pre>
</div>
</div>
<p>Os resultados indicam que, no primeiro cenário, a TMI média esperada é aproximadamente 35,96 óbitos por mil nascidos vivos, com intervalo de confiança entre 34,58 e 37,34.</p>
<p>No segundo cenário, a TMI média estimada é aproximadamente 18,20, com intervalo entre 16,80 e 19,60.</p>
<p>No terceiro cenário, a TMI média estimada é aproximadamente 1,10, com intervalo entre -0,63 e 2,84.</p>
<p>Observa-se, portanto, uma redução consistente da taxa de mortalidade infantil à medida que os indicadores socioeconômicos apresentam melhora.</p>
</section>
<section id="intervalo-de-predição" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="intervalo-de-predição"><span class="header-section-number">8.3</span> Intervalo de Predição</h2>
<p>Um <strong>intervalo de predição</strong> captura a incerteza associada à previsão de <strong>uma observação individual</strong>, e não apenas do valor médio esperado.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>tab_IP <span class="ot">&lt;-</span> <span class="fu">predict</span>(</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  modelo_final,</span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  novas.preditoras,</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">interval =</span> <span class="st">"prediction"</span></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>tab_IP <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(tab_IP, <span class="at">row.names =</span> <span class="cn">NULL</span>)</span>
<span id="cb62-8"><a href="#cb62-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-9"><a href="#cb62-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(tab_IP) <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb62-10"><a href="#cb62-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Valor_Previsto"</span>,</span>
<span id="cb62-11"><a href="#cb62-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Limite_Inferior_Prev"</span>,</span>
<span id="cb62-12"><a href="#cb62-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">"Limite_Superior_Prev"</span></span>
<span id="cb62-13"><a href="#cb62-13" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb62-14"><a href="#cb62-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-15"><a href="#cb62-15" aria-hidden="true" tabindex="-1"></a>tab_IP</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Valor_Previsto Limite_Inferior_Prev Limite_Superior_Prev
1      35.962273            30.444991            41.479554
2      18.197336            12.675196            23.719476
3       1.104733            -4.513079             6.722545</code></pre>
</div>
</div>
<p>Os resultados indicam que, no primeiro cenário, a TMI prevista é aproximadamente 35,96, com intervalo de predição entre 30,44 e 41,48.</p>
<p>No segundo cenário, a previsão é aproximadamente 18,20, com intervalo entre 12,68 e 23,72.</p>
<p>No terceiro cenário, a previsão é aproximadamente 1,10, com intervalo entre -4,51 e 6,72.</p>
<p>Observa-se que os intervalos de predição são mais amplos que os intervalos de confiança, refletindo a variabilidade individual presente nos dados.</p>
<p>No terceiro cenário, o limite inferior do intervalo de predição assume valor negativo. Como a taxa de mortalidade infantil não pode assumir valores negativos na prática, esse resultado deve ser interpretado como uma indicação de que a mortalidade prevista é muito próxima de zero. Esse comportamento ocorre porque o modelo de regressão linear não impõe restrições ao intervalo de valores possíveis da variável resposta.</p>
</section>
<section id="comparação-entre-intervalos" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="comparação-entre-intervalos"><span class="header-section-number">8.4</span> Comparação entre Intervalos</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>tab_IC_e_IP <span class="ot">&lt;-</span> <span class="fu">cbind.data.frame</span>(tab_IC, tab_IP)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>tab_IC_e_IP <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 14%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Media_Prevista</th>
<th style="text-align: right;">Limite_Inferior</th>
<th style="text-align: right;">Limite_Superior</th>
<th style="text-align: right;">Valor_Previsto</th>
<th style="text-align: right;">Limite_Inferior_Prev</th>
<th style="text-align: right;">Limite_Superior_Prev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">35.962273</td>
<td style="text-align: right;">34.582894</td>
<td style="text-align: right;">37.341652</td>
<td style="text-align: right;">35.962273</td>
<td style="text-align: right;">30.444991</td>
<td style="text-align: right;">41.479554</td>
</tr>
<tr class="even">
<td style="text-align: right;">18.197336</td>
<td style="text-align: right;">16.798650</td>
<td style="text-align: right;">19.596021</td>
<td style="text-align: right;">18.197336</td>
<td style="text-align: right;">12.675196</td>
<td style="text-align: right;">23.719476</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1.104733</td>
<td style="text-align: right;">-0.633686</td>
<td style="text-align: right;">2.843153</td>
<td style="text-align: right;">1.104733</td>
<td style="text-align: right;">-4.513078</td>
<td style="text-align: right;">6.722545</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A comparação entre os resultados mostra que os intervalos de predição são sistematicamente mais amplos do que os intervalos de confiança para os cenários analisados.</p>
<p>Por exemplo, no primeiro cenário o intervalo de confiança varia entre 34,58 e 37,34, enquanto o intervalo de predição se estende de aproximadamente 30,44 a 41,48.</p>
<p>Esse padrão se repete nos demais cenários, evidenciando que a incerteza associada à previsão de valores individuais é maior do que aquela relacionada à estimativa do valor médio esperado da variável resposta.</p>
<p>Esses resultados reforçam a importância de distinguir entre inferência sobre valores médios populacionais e previsão de observações individuais ao interpretar os resultados de modelos de regressão.</p>
</section>
<section id="conclusão" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="conclusão"><span class="header-section-number">8.5</span> Conclusão</h2>
<p>A análise realizada por meio do modelo de regressão linear permitiu identificar associações relevantes entre a taxa de mortalidade infantil e diferentes indicadores socioeconômicos e de infraestrutura. De forma geral, observou-se que melhores condições de desenvolvimento — como maior acesso ao saneamento, maior renda per capita, menor taxa de analfabetismo e melhores indicadores de saúde — estão associadas a menores níveis de mortalidade infantil.</p>
<p>As previsões realizadas para cenários hipotéticos reforçam esse padrão, evidenciando uma redução consistente na taxa de mortalidade infantil à medida que os indicadores socioeconômicos apresentam melhoria. Observa-se ainda que os intervalos de predição são mais amplos do que os intervalos de confiança, refletindo a maior incerteza associada à previsão de observações individuais.</p>
<p>Apesar de algumas limitações inerentes ao modelo de regressão linear — como a possibilidade de gerar valores previstos fora do intervalo plausível da variável resposta — os resultados obtidos fornecem evidências consistentes sobre a relação entre condições socioeconômicas e mortalidade infantil.</p>
<p>De maneira geral, os resultados destacam a importância de políticas públicas voltadas à melhoria das condições de saneamento, educação, renda e acesso aos serviços de saúde como estratégias fundamentais para a redução da mortalidade infantil.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>